version: '3.8'

services:
  nextjs:
    container_name: nextjs_app_${COMPOSE_PROJECT_NAME:-default}
    build:
      context: .
      dockerfile: Dockerfile-fe
    ports:
      - "3000:3000"
    env_file:
      - .env-fe
    restart: always
