# Stage 1: Build the application
FROM node:18-alpine AS builder

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy application code
COPY . .

# 환경 변수 파일 설정
ENV DOTENV_CONFIG_PATH=/app/.env-fe

# Build the application
RUN npm run build

# Stage 2: Create a lightweight production image
FROM node:18-alpine

WORKDIR /app

# Copy built application from builder stage
COPY --from=builder /app ./

# Expose port 3000
EXPOSE 3000

# Run the Next.js application
CMD ["npm", "run", "start"]



