// // ------------------
// // API 연동 전 더미데이터 임시 저장
// // API 연동 후 삭제할 것!

// export const pageSearch: DubbingRoom[] = [
//   {
//     id: 1,
//     //thumbnail: "https://picsum.photos/seed/picsum/300/200",
//     title: "더빙룸 필터.",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
// ];

// export const pageDefault: DubbingRoom[] = [
//   {
//     id: 1,
//     title: "짱구 더빙하실 분",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: true,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [3, 4, 5],
//     categories: [6],
//   },
//   {
//     id: 2,
//     title: "코난 더빙하실 분",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: true,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [5],
//     categories: [1, 2, 3, 4, 5, 6, 7, 8],
//   },
//   {
//     id: 3,
//     title: "드라마 더빙 모임",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: true,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [3, 4],
//     categories: [7, 3],
//   },
//   {
//     id: 4,
//     title: "판타지 더빙 모임",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1],
//     categories: [3, 4],
//   },
//   {
//     id: 5,
//     title: "공포 더빙 모임",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [4],
//     categories: [5, 6],
//   },
//   {
//     id: 6,
//     title: "일상 더빙 모임",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [3, 5],
//     categories: [5],
//   },
//   {
//     id: 7,
//     title: "코믹 더빙 모임",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 8,
//     title: "로맨스 더빙 모임",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 9,
//     title: "액션 더빙 모임",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 10,
//     title: "다큐멘터리 더빙 모임",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 11,
//     title: "스릴러 더빙 모임",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 12,
//     title: "판타지 더빙 모임",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 13,
//     title: "광고 더빙 모임",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 14,
//     title: "애니메이션 더빙 모임",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 15,
//     title: "스릴러 더빙 모임",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 16,
//     title: "더빙 모임 16",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 17,
//     title: "더빙 모임 17",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 18,
//     title: "더빙 모임 18",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 19,
//     title: "더빙 모임 19",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 20,
//     title: "더빙 모임 20",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 21,
//     title: "더빙 모임 21",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 22,
//     title: "더빙 모임 22",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 23,
//     title: "더빙 모임 23",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 24,
//     title: "더빙 모임 24",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 25,
//     title: "더빙 모임 25",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 26,
//     title: "더빙 모임 26",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 27,
//     title: "더빙 모임 27",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 28,
//     title: "더빙 모임 28",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 29,
//     title: "더빙 모임 29",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 30,
//     title: "더빙 모임 30",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 31,
//     title: "더빙 모임 31",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [5],
//     categories: [1, 7, 8],
//   },
//   {
//     id: 32,
//     title: "더빙 모임 32",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 4,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 33,
//     title: "더빙 모임 33",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 34,
//     title: "더빙 모임 34",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 35,
//     title: "더빙 모임 35",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
//   {
//     id: 36,
//     title: "더빙 모임 36",
//     startTime: "03/20:14:00",
//     endTime: "03/20:14:00",
//     onAir: false,
//     isRecruiting: true,
//     totalParticipants: 6,
//     currentParticipants: 2,
//     authorId: 1,
//     genres: [1, 2],
//     categories: [2, 4, 5],
//   },
// ];
