#server:
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: file:/app/ssafy-web.p12
#    key-store-password: ${SSL_KEYSTORE_PASSWORD}
#    key-alias: ssafy-web

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    show-sql: false  # 배포 환경에서는 SQL 로그 비활성화

logging:
  level:
    # SQL 쿼리 로그
    org.hibernate.sql: debug  # 실행되는 쿼리
    org.hibernate.type.descriptor.sql: trace  # 쿼리 파라미터

    # Security 관련 로그
    org.springframework.security: DEBUG
    com.ssafy.dubdub.security: DEBUG
    com.ssafy.dubdub.security.jwt.JwtAuthenticationFilter: DEBUG  # JWT 필터 로그

    # 웹 요청/응답 로그
    org.springframework.web: DEBUG

