server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      force-response: true

spring:
  application:
    name: dubdub
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_ENDPOINT}:3306/${RDS_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    show-sql: true

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.type: trace
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace

